development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: blog_production
  pool: 5
  username: blog
  password:
